name: .NET Game Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    # Автоматически ставим .NET 9, так как в логах видно, что ваш проект использует net9.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    # Публикуем конкретный проект игры, отключая сбойную оптимизацию размера (PublishTrimmed=false)
    - name: Publish Game
      run: |
        dotnet publish ./Game/Engine.csproj --configuration Release -p:PublishTrimmed=false --output ./publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-build-linux
        path: ./publish
