name: .NET Game Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted # Убедитесь, что здесь указано self-hosted для вашего сервера

    steps:
    - uses: actions/checkout@v4

    # Шаг Setup .NET удален, так как он установлен глобально на сервере

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Game
      run: |
        dotnet publish ./Game/Engine.csproj --configuration Release -p:PublishTrimmed=true --output ./publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-build-linux
        path: ./publish
